### ISSUE TITLE
Can't compile it now

### ISSUE THREAD

**Issue by emmansun** [ruks/wso2-am-billing-engine#4]
[WARNING] The POM for org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.impl:jar:5.0.4-SNAPSHOT is missing, no dependency information available
Downloading: http://maven.wso2.org/nexus/content/groups/wso2-public/org/wso2/carbon/apimgt/org.wso2.carbon.apimgt.impl/5.0.4-SNAPSHOT/org.wso2.carbon.apimgt.impl-5.0.4-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] billing-sample ..................................... SUCCESS [  0.005 s]
[INFO] WSO2 APIM Billing Engine ........................... SUCCESS [15:48 min]
[INFO] subs-workflow ...................................... FAILURE [  8.060 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:56 min
[INFO] Finished at: 2016-08-11T16:47:39+08:00
[INFO] Final Memory: 22M/152M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project subs-workflow: Could not resolve dependencies for project org.wso2.apim.sample:subs-workflow:jar:1.0-SNAPSHOT: Could not find artifact org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.impl:jar:5.0.4-SNAPSHOT in wso2-nexus (http://maven.wso2.org/nexus/content/groups/wso2-public/) -

> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :subs-workflow

BTW, Can it work with APIM 2.0.0?

**Comment by emmansun** [comment]
Changed the org.wso2.carbon.apimgt.impl to **6.0.0** in subs-billing-workflow\pom.xml,

**Comment by ruks** [comment]
Hi emmansun,

If you want to work this with you need to use org.wso2.carbon.apimgt.impl 5.0.3 version. I made that change and you can use it now.

Yes you can use with 2.0.0. But before that you need to org.wso2.carbon.apimgt.impl  6.0.4.

Thanks.

**Comment by emmansun** [comment]
Hi ruks,

Could you kindly help to take a look for http://stackoverflow.com/questions/38909535/article-enabling-monetization-of-apis-with-wso2-api-manager-related-question ? 

Thanks in advance!

**Comment by emmansun** [comment]
Hi Ruks, 

Thx for your answer. in the sample app and the article , when consumer subscribe the API, he/she will be redirect to billing engine and input information(include username/password, if it's different with username in WSO2 APIM, what will happen). And then the consumer can login to billing engine for further definition. 

So i will ask question 1: "Is the sample billing engine used by API subscriber?".
