### ISSUE TITLE
APIM Billing Engine: user should not be able to define new plans

### ISSUE THREAD

**Issue by pcalero** [ruks/wso2-am-billing-engine#8]
**Description:**
Currently, after install and configure Billing Workflow and Billing Engine, API subscriber user can log in the Billing Engine and define new plans, even generate invoices.

**Suggested Labels:**
Type/Bug
Severity/Major
wso2-am-billing-engine

**Suggested Assignees:**
@ruks 

**Affected Product Version:**
All

**OS, DB, other environment details and versions:**    
In my case, I am using WSO2 API Manager 2.5.0 and wso2-am-billing-engine branch 2.2.0 (**apim-billing-engine 1.3.0**)

**Steps to reproduce:**
In a environment where Billing Engine and Billing Working are installed and configured following [doc](https://docs.wso2.com/display/AM250/Enabling+Monetization+of+APIs).
1. User sign up and log in
2. User subscribe to an API, and it is redirected to the Billing Engine. After sign up in Billing Engine, it is redirected to the Store.
3. If the user go again to the URL of Billing Engine, he/she can log in and define new billing plans, generate invoices, etc.

**Related Issues:**
https://stackoverflow.com/questions/53535662/monetization-and-billing-in-wso-api-manager-concepts
https://stackoverflow.com/questions/38909535/article-enabling-monetization-of-apis-with-wso2-api-manager-related-question
https://stackoverflow.com/questions/53121231/in-wso2-api-monetization-why-subscriber-will-fill-details-regarding-plan
https://github.com/wso2/product-apim/issues/1045

**Comment by ruks** [comment]
Close the issue since wso2-am-billing-engine is depricated
